### ISSUE TITLE
TheodoliteFeed memory usage and crash

### ISSUE THREAD

**Issue by zdnk** [TheodoliteGroup/Theodolite#29] opened 2018-02-17 18:27 UTC
Hello,
first of all - Nice work! I love what you do and looking forward for v1!

Anyway, I checked the TheodoliteFeed example and I feel like it is using a lot of memory, like I got to 450MB in iPhone 8 simulator.
Also you are forcing the article to have an image, some don't and the app crashes without modifications to the code.

Keep up the good work!
Zdenek

**Comment by ocrickard** [comment] 2018-02-17 18:30
Great points! I’ll take a look soon!

**Comment by zdenektopic** [comment] 2018-02-17 18:32
One more thing, the Playground workspace is also broken, the playgrounds are missing which is shame, it would be lovely to have a playground to play with and simply try the features :)

**Comment by ocrickard** [comment] 2018-02-17 18:35
Yeah I didn’t finish the playgrounds. I’m not too familiar with making playgrounds. Any interest in helping me out and building a simple one?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zdenektopic** [comment] 2018-02-17 19:12
Yeah I can do something in spare time. Do you have any idea on what would you like to have in the playground?

**Comment by ocrickard** [comment] 2018-02-17 21:25
Our traditional demo is a "kittens feed" lol... so something to do with kittens?

**Comment by ocrickard** [comment] 2018-02-17 21:35
Re memory consumption, looks like the primary cause of the issue is in the in-memory storage of the image data. See attached image.

<img width="1020" alt="screen shot 2018-02-17 at 4 28 14 pm" src="https://user-images.githubusercontent.com/857665/36345801-e2f15b6e-13ff-11e8-8a1b-2e7426a8347e.png">

The image data is all held in-memory, and it looks like the size of the images from these news articles is really, really big. Couple potential solutions came to mind:

1. If this were a real application I would down-scale the images, and use a write-through LRU cache to persist to disk and then load from disk as needed.
2. But since this is a basic demo, I can just downscale the images and try keeping them in-memory. Should work.

Anyway, doesn't look like the framework is responsible for the memory load here, just my iffy demo code. Yay! Glad I didn't have any huge leaks.

We do have a couple small retain-cycles in the demo code, but they're quite small. Will break them.

**Comment by zdenektopic** [comment] 2018-02-17 21:45
Yep, I came to same conclusion. Anyway, what happens - the images are sort of downloaded all at once right away when the application is ran even the components are not visible, that is maybe a little disturbing and does not show a good example of usage.

**Comment by ocrickard** [comment] 2018-02-17 21:55
> the images are sort of downloaded all at once right away when the application is ran even the components are not visible, that is maybe a little disturbing and does not show a good example of usage.

haha, surprisingly enough, downloading them all at once right away is how most major apps work. They tend to just build efficient caching layers. I've seen numerous attempts at building more efficient systems, but it always impacts engagement.

Anyway, I'll reduce the memory load.

**Comment by zdenektopic** [comment] 2018-02-17 22:07
I see. 

Well in my experience, the apps usually start fetching the images just before they are supposed to be displayed (majority of apps) or have some extended prefetching model implemented with range controllers etc, but not downloading everything right away, it does not actually makes sense as it lowers the UX from the point of view that you are waiting longer to see the images that you are supposed to see on screen right in the moment because a lot other images is being downloaded at the same time, of course queue and concurrency limiting can applied to improve the UX.

My point is that the example should maybe reflect the most common implementation that the developers are used to. I would not even build cache layer - simply just use default behaviour of http/NSURLSession caching.

**Comment by ocrickard** [comment] 2018-02-17 22:17
Cool, it's trivial to implement a simple working range system as I did for IGListKit. We could just pull something like that in if that's what you want. I also implemented that system for IG itself, FB, Messenger, Paper, but unfortunately we could never ship image prefetching on that system. Open to trying it again though!

**Comment by ocrickard** [comment] 2018-02-17 22:17
In any event, I'm on the memory reductions. Thanks for reporting!

**Comment by ocrickard** [comment] 2018-02-17 22:28
@kfirapps sounds like @zdenektopic wants working ranges for Theodolite. Any interest in hacking on it?

**Comment by kfirapps** [comment] 2018-02-18 14:29
Hey @ocrickard, it could be a really cool project for Thedolite! However, I'm not sure I'm going to have time in the next weeks.
If you start working on this, I'd suggest to integrate the working range configuration in a similar way to the view configuration - make it a base configuration for every component; similar to Litho's visibility events: https://fblitho.com/docs/visibility-handling.

**Comment by ocrickard** [comment] 2019-04-13 17:34
Alright, since the example project has much reduced memory consumption, I'm going to close this. This is something that should be handled in user-space, not at the framework level. Perhaps a good excuse for a higher-level tool/framework though!

**Closed by ocrickard** 2019-04-13 17:34 UTC
Labels: bug
